[package]
name = "checkupgrades"
version = "0.1.3"
edition = "2021"

[dependencies]
anyhow = "1"
atty = "0.2"
bstr = "0.2"
clap = { version = "3.2", features = ["cargo", "derive"] }
libc = "0.2"
once_cell = "1.13"
regex = "1.6"
termcolor = "1"
