[package]
name = "checkupgrades"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
bstr = "1"
clap = { version = "4.1", features = ["cargo"] }
is-terminal = "0.4"
libc = "0.2"
once_cell = "1.13"
regex = "1.6"
termcolor = "1"
