[package]
name = "checkupgrades"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1"
atty = "0.2"
bstr = "0.2"
clap = { version = "3.2", features = ["cargo", "derive"] }
lazy_static = "1"
libc = "0.2"
regex = "1.6"
termcolor = "1"
